name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup up Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pre-commit pytest

            - name: Run pre-commit hooks
              run: pre-commit run --all-files

            - name: Run tests
              run: pytest

    build-docker:
        runs-on: ubuntu-latest
        needs: lint-test

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t sentiment-analyzer:latest .
